### ISSUE TITLE
coax.py: UnboundLocalError: local variable 'start' referenced before assignment

### ISSUE THREAD

**Issue by biergaizi** [matthuszagh/pyems#47]
I was trying to run the demo coax.py, unfortunately it fails.

```
Traceback (most recent call last):
  File "/home/user/code/pyems/examples/coax.py", line 34, in <module>
    Coax(
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/structure.py", line 2653, in __init__
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/structure.py", line 2663, in construct
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/structure.py", line 2671, in _construct_core
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/structure.py", line 2688, in _construct_port_core
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/port.py", line 1671, in __init__
  File "/home/user/.local/lib/python3.9/site-packages/pyems-0.1.0-py3.9.egg/pyems/port.py", line 1716, in _set_core
UnboundLocalError: local variable 'start' referenced before assignment
```

**Comment by matthuszagh** [comment]
Thanks for reporting. This should now be fixed in 11439b92b7bd748ca99e151a8a9f35f5c4372da8. Feel free to reopen if you're still experiencing issues.
