### ISSUE TITLE
differential_gcpw.py & differential_gcpw_blocking_cap.py: TypeError: __init__() got an unexpected keyword argument 'via_gap'

### ISSUE THREAD

**Issue by biergaizi** [matthuszagh/pyems#48]
I was trying to run the demo differential_gcpw.py & differential_gcpw_blocking_cap.py, unfortunately they fail.

differential_gcpw.py

```
Traceback (most recent call last):
  File "/home/user/code/pyems/examples/differential_gcpw.py", line 34, in <module>
    DifferentialMicrostrip(
TypeError: __init__() got an unexpected keyword argument 'via_gap'
```

differential_gcpw_blocking_cap.py

```
Traceback (most recent call last):
  File "/home/user/code/pyems/examples/gcpw_bypass_cap.py", line 33, in <module>
    Microstrip(
TypeError: __init__() got an unexpected keyword argument 'via_gap'
```

**Comment by matthuszagh** [comment]
Fixed 2ec83de0e8d7af59ae4e3fbc0a781c77be600f15.
